debian-style init script for flapjack v1

diff --git a/dist/etc/init.d/v1/flapjack b/dist/etc/init.d/v1/flapjack
--- a/dist/etc/init.d/v1/flapjack
+++ b/dist/etc/init.d/v1/flapjack
@@ -17,6 +17,15 @@
 # Boots flapjack (coordinator, processor, notifier, gateways...)
 
 PATH=/opt/flapjack/bin:$PATH
+DAEMON=/opt/flapjack/bin/flapjack
+DAEMON_ARGS=server
+NAME=flapjack
+DESC=flapjack
+
+RUNDIR=/var/run/flapjack
+PIDFILE=$RUNDIR/$NAME.pid
+
+chown flapjack:flapjack $RUNDIR $PIDFILE
 
 if ! type flapjack > /dev/null 2>&1; then
   echo "Error: flapjack isn't in PATH."
@@ -24,8 +33,44 @@ if ! type flapjack > /dev/null 2>&1; then
   exit 1
 fi
 
-# Evaluate command
-flapjack server $@
+case "$1" in
+  start)
+  if start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid flapjack:flapjack --exec $DAEMON -- $DAEMON_ARGS start; then
+    echo "$NAME."
+  else
+    echo "failed"
+    exit 1
+    fi
+  ;;
 
-RETVAL=$?
-exit $RETVAL
+  stop)
+  if start-stop-daemon --stop --retry TERM/15/KILL/10 --quiet --oknodo --pidfile $PIDFILE; then
+    echo "$NAME."
+  else
+    echo "failed"
+    exit 1
+  fi
+  ;;
+
+  restart|force-reload)
+  ${0} stop
+  ${0} start
+  ;;
+
+  status)
+  if start-stop-daemon --status --quiet --signal 0 --name $NAME --pidfile $PIDFILE; then
+    $DAEMON server status
+  else
+    echo "not running"
+    exit 1
+  fi
+  ;;
+
+  *)
+  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+  exit 1
+  ;;
+
+esac
+
+exit 0
